openapi: 3.0.0
info:
  title: API работы с бонусами
  version: 1.0.0
  description: " "
  contact:
    name: ООО "Минимаркет"
    email: minimarket@admin.com
    url: https://github.com/PiskarevSA/minimarket-auth
servers:
  - url: https://127.0.0.1:8616
    description: Локальный сервер для тестов
tags:
  - name: Points

paths:
  /api/user/balance:
    $ref: paths/get-balance.yaml

  /api/user/balance/deposit:
    $ref: paths/deposit.yaml

  /api/user/balance/withdraw:
    $ref: paths/withdraw.yaml

  /api/user/withdrawals:
    $ref: paths/get-withdrawals.yaml

components:
  securitySchemes:
    $ref: headers/Security.yaml