version: "2"

linters:
  default: all
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - copyloopvar
  - cyclop
  - depguard
  - dupl
  - durationcheck
  - errcheck
  - errname
  - errorlint
  - exptostd
  - fatcontext
  - forbidigo
  - funcorder
  - funlen
  - gocheckcompilerdirectives
  - gochecknoglobals
  - gochecknoinits
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - gomoddirectives
  - goprintffuncname
  - gosec
  - govet
  - iface
  - ineffassign
  - intrange
  - loggercheck
  - makezero
  - mirror
  - mnd
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilnesserr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - perfsprint
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - recvcheck
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - testableexamples
  - testifylint
  - testpackage
  - tparallel
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - usetesting
  - wastedassign
  - whitespace
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

formatters:
  enable:
  - goimports
  - golines
  settings:
    goimports:
      local-prefixes:
      - github.com/PiskarevSA/
    golines:
      max-len: 80