version: '3.0'

includes:
  oapi-codegen: 
    taskfile: taskfiles/OapiCodegen.yaml
    internal: true

  sqlc:
    taskfile: taskfiles/Sqlc.yaml
    internal: true

vars:
  ROOT:
    sh: pwd

tasks:
  generate:oapi:
    desc: |
      Генерирует шаблонный код Go HTTP сервера на основе спецификации
      формата OpenAPI при помощи oapi-codegen.
    cmds:
      - task: oapi-codegen:run:codegen
  
  generate:sqlc:
    desc: |
      Генерирует Go код для взаимодействия с базой данных на основе 
      SQL кода при помощи SQLc. 
    cmds:
      - task: sqlc:run:codegen
