// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package usecases

import (
	"context"
	"sync"
	"time"

	"github.com/PiskarevSA/minimarket-points/internal/domain/entities"
	"github.com/PiskarevSA/minimarket-points/internal/domain/objects"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// Ensure that MockGetBalanceRepo does implement GetBalanceRepo.
// If this is not the case, regenerate this file with mockery.
var _ GetBalanceRepo = &MockGetBalanceRepo{}

// MockGetBalanceRepo is a mock implementation of GetBalanceRepo.
//
//	func TestSomethingThatUsesGetBalanceRepo(t *testing.T) {
//
//		// make and configure a mocked GetBalanceRepo
//		mockedGetBalanceRepo := &MockGetBalanceRepo{
//			GetBalanceFunc: func(ctx context.Context, userId uuid.UUID) (objects.Balance, error) {
//				panic("mock out the GetBalance method")
//			},
//		}
//
//		// use mockedGetBalanceRepo in code that requires GetBalanceRepo
//		// and then make assertions.
//
//	}
type MockGetBalanceRepo struct {
	// GetBalanceFunc mocks the GetBalance method.
	GetBalanceFunc func(ctx context.Context, userId uuid.UUID) (objects.Balance, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetBalance holds details about calls to the GetBalance method.
		GetBalance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserId is the userId argument value.
			UserId uuid.UUID
		}
	}
	lockGetBalance sync.RWMutex
}

// GetBalance calls GetBalanceFunc.
func (mock *MockGetBalanceRepo) GetBalance(ctx context.Context, userId uuid.UUID) (objects.Balance, error) {
	if mock.GetBalanceFunc == nil {
		panic("MockGetBalanceRepo.GetBalanceFunc: method is nil but GetBalanceRepo.GetBalance was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserId uuid.UUID
	}{
		Ctx:    ctx,
		UserId: userId,
	}
	mock.lockGetBalance.Lock()
	mock.calls.GetBalance = append(mock.calls.GetBalance, callInfo)
	mock.lockGetBalance.Unlock()
	return mock.GetBalanceFunc(ctx, userId)
}

// GetBalanceCalls gets all the calls that were made to GetBalance.
// Check the length with:
//
//	len(mockedGetBalanceRepo.GetBalanceCalls())
func (mock *MockGetBalanceRepo) GetBalanceCalls() []struct {
	Ctx    context.Context
	UserId uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserId uuid.UUID
	}
	mock.lockGetBalance.RLock()
	calls = mock.calls.GetBalance
	mock.lockGetBalance.RUnlock()
	return calls
}

// Ensure that MockTransactor does implement Transactor.
// If this is not the case, regenerate this file with mockery.
var _ Transactor = &MockTransactor{}

// MockTransactor is a mock implementation of Transactor.
//
//	func TestSomethingThatUsesTransactor(t *testing.T) {
//
//		// make and configure a mocked Transactor
//		mockedTransactor := &MockTransactor{
//			TransactFunc: func(ctx context.Context, opts pgx.TxOptions, fn func(ctx context.Context) error) error {
//				panic("mock out the Transact method")
//			},
//		}
//
//		// use mockedTransactor in code that requires Transactor
//		// and then make assertions.
//
//	}
type MockTransactor struct {
	// TransactFunc mocks the Transact method.
	TransactFunc func(ctx context.Context, opts pgx.TxOptions, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Transact holds details about calls to the Transact method.
		Transact []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts pgx.TxOptions
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockTransact sync.RWMutex
}

// Transact calls TransactFunc.
func (mock *MockTransactor) Transact(ctx context.Context, opts pgx.TxOptions, fn func(ctx context.Context) error) error {
	if mock.TransactFunc == nil {
		panic("MockTransactor.TransactFunc: method is nil but Transactor.Transact was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts pgx.TxOptions
		Fn   func(ctx context.Context) error
	}{
		Ctx:  ctx,
		Opts: opts,
		Fn:   fn,
	}
	mock.lockTransact.Lock()
	mock.calls.Transact = append(mock.calls.Transact, callInfo)
	mock.lockTransact.Unlock()
	return mock.TransactFunc(ctx, opts, fn)
}

// TransactCalls gets all the calls that were made to Transact.
// Check the length with:
//
//	len(mockedTransactor.TransactCalls())
func (mock *MockTransactor) TransactCalls() []struct {
	Ctx  context.Context
	Opts pgx.TxOptions
	Fn   func(ctx context.Context) error
} {
	var calls []struct {
		Ctx  context.Context
		Opts pgx.TxOptions
		Fn   func(ctx context.Context) error
	}
	mock.lockTransact.RLock()
	calls = mock.calls.Transact
	mock.lockTransact.RUnlock()
	return calls
}

// Ensure that MockCreateOrUpdateBalanceInRepo does implement CreateOrUpdateBalanceInRepo.
// If this is not the case, regenerate this file with mockery.
var _ CreateOrUpdateBalanceInRepo = &MockCreateOrUpdateBalanceInRepo{}

// MockCreateOrUpdateBalanceInRepo is a mock implementation of CreateOrUpdateBalanceInRepo.
//
//	func TestSomethingThatUsesCreateOrUpdateBalanceInRepo(t *testing.T) {
//
//		// make and configure a mocked CreateOrUpdateBalanceInRepo
//		mockedCreateOrUpdateBalanceInRepo := &MockCreateOrUpdateBalanceInRepo{
//			CreateOrUpdateBalanceInTxFunc: func(ctx context.Context, userId uuid.UUID, operation objects.Operation, amount objects.Amount, updatedAt time.Time) error {
//				panic("mock out the CreateOrUpdateBalanceInTx method")
//			},
//		}
//
//		// use mockedCreateOrUpdateBalanceInRepo in code that requires CreateOrUpdateBalanceInRepo
//		// and then make assertions.
//
//	}
type MockCreateOrUpdateBalanceInRepo struct {
	// CreateOrUpdateBalanceInTxFunc mocks the CreateOrUpdateBalanceInTx method.
	CreateOrUpdateBalanceInTxFunc func(ctx context.Context, userId uuid.UUID, operation objects.Operation, amount objects.Amount, updatedAt time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrUpdateBalanceInTx holds details about calls to the CreateOrUpdateBalanceInTx method.
		CreateOrUpdateBalanceInTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserId is the userId argument value.
			UserId uuid.UUID
			// Operation is the operation argument value.
			Operation objects.Operation
			// Amount is the amount argument value.
			Amount objects.Amount
			// UpdatedAt is the updatedAt argument value.
			UpdatedAt time.Time
		}
	}
	lockCreateOrUpdateBalanceInTx sync.RWMutex
}

// CreateOrUpdateBalanceInTx calls CreateOrUpdateBalanceInTxFunc.
func (mock *MockCreateOrUpdateBalanceInRepo) CreateOrUpdateBalanceInTx(ctx context.Context, userId uuid.UUID, operation objects.Operation, amount objects.Amount, updatedAt time.Time) error {
	if mock.CreateOrUpdateBalanceInTxFunc == nil {
		panic("MockCreateOrUpdateBalanceInRepo.CreateOrUpdateBalanceInTxFunc: method is nil but CreateOrUpdateBalanceInRepo.CreateOrUpdateBalanceInTx was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserId    uuid.UUID
		Operation objects.Operation
		Amount    objects.Amount
		UpdatedAt time.Time
	}{
		Ctx:       ctx,
		UserId:    userId,
		Operation: operation,
		Amount:    amount,
		UpdatedAt: updatedAt,
	}
	mock.lockCreateOrUpdateBalanceInTx.Lock()
	mock.calls.CreateOrUpdateBalanceInTx = append(mock.calls.CreateOrUpdateBalanceInTx, callInfo)
	mock.lockCreateOrUpdateBalanceInTx.Unlock()
	return mock.CreateOrUpdateBalanceInTxFunc(ctx, userId, operation, amount, updatedAt)
}

// CreateOrUpdateBalanceInTxCalls gets all the calls that were made to CreateOrUpdateBalanceInTx.
// Check the length with:
//
//	len(mockedCreateOrUpdateBalanceInRepo.CreateOrUpdateBalanceInTxCalls())
func (mock *MockCreateOrUpdateBalanceInRepo) CreateOrUpdateBalanceInTxCalls() []struct {
	Ctx       context.Context
	UserId    uuid.UUID
	Operation objects.Operation
	Amount    objects.Amount
	UpdatedAt time.Time
} {
	var calls []struct {
		Ctx       context.Context
		UserId    uuid.UUID
		Operation objects.Operation
		Amount    objects.Amount
		UpdatedAt time.Time
	}
	mock.lockCreateOrUpdateBalanceInTx.RLock()
	calls = mock.calls.CreateOrUpdateBalanceInTx
	mock.lockCreateOrUpdateBalanceInTx.RUnlock()
	return calls
}

// Ensure that MockCreateTransactionRepo does implement CreateTransactionRepo.
// If this is not the case, regenerate this file with mockery.
var _ CreateTransactionRepo = &MockCreateTransactionRepo{}

// MockCreateTransactionRepo is a mock implementation of CreateTransactionRepo.
//
//	func TestSomethingThatUsesCreateTransactionRepo(t *testing.T) {
//
//		// make and configure a mocked CreateTransactionRepo
//		mockedCreateTransactionRepo := &MockCreateTransactionRepo{
//			CreateTransactionInTxFunc: func(ctx context.Context, userId uuid.UUID, orderNumber objects.OrderNumber, operation objects.Operation, amount objects.Amount, timestamp time.Time) error {
//				panic("mock out the CreateTransactionInTx method")
//			},
//		}
//
//		// use mockedCreateTransactionRepo in code that requires CreateTransactionRepo
//		// and then make assertions.
//
//	}
type MockCreateTransactionRepo struct {
	// CreateTransactionInTxFunc mocks the CreateTransactionInTx method.
	CreateTransactionInTxFunc func(ctx context.Context, userId uuid.UUID, orderNumber objects.OrderNumber, operation objects.Operation, amount objects.Amount, timestamp time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateTransactionInTx holds details about calls to the CreateTransactionInTx method.
		CreateTransactionInTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserId is the userId argument value.
			UserId uuid.UUID
			// OrderNumber is the orderNumber argument value.
			OrderNumber objects.OrderNumber
			// Operation is the operation argument value.
			Operation objects.Operation
			// Amount is the amount argument value.
			Amount objects.Amount
			// Timestamp is the timestamp argument value.
			Timestamp time.Time
		}
	}
	lockCreateTransactionInTx sync.RWMutex
}

// CreateTransactionInTx calls CreateTransactionInTxFunc.
func (mock *MockCreateTransactionRepo) CreateTransactionInTx(ctx context.Context, userId uuid.UUID, orderNumber objects.OrderNumber, operation objects.Operation, amount objects.Amount, timestamp time.Time) error {
	if mock.CreateTransactionInTxFunc == nil {
		panic("MockCreateTransactionRepo.CreateTransactionInTxFunc: method is nil but CreateTransactionRepo.CreateTransactionInTx was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UserId      uuid.UUID
		OrderNumber objects.OrderNumber
		Operation   objects.Operation
		Amount      objects.Amount
		Timestamp   time.Time
	}{
		Ctx:         ctx,
		UserId:      userId,
		OrderNumber: orderNumber,
		Operation:   operation,
		Amount:      amount,
		Timestamp:   timestamp,
	}
	mock.lockCreateTransactionInTx.Lock()
	mock.calls.CreateTransactionInTx = append(mock.calls.CreateTransactionInTx, callInfo)
	mock.lockCreateTransactionInTx.Unlock()
	return mock.CreateTransactionInTxFunc(ctx, userId, orderNumber, operation, amount, timestamp)
}

// CreateTransactionInTxCalls gets all the calls that were made to CreateTransactionInTx.
// Check the length with:
//
//	len(mockedCreateTransactionRepo.CreateTransactionInTxCalls())
func (mock *MockCreateTransactionRepo) CreateTransactionInTxCalls() []struct {
	Ctx         context.Context
	UserId      uuid.UUID
	OrderNumber objects.OrderNumber
	Operation   objects.Operation
	Amount      objects.Amount
	Timestamp   time.Time
} {
	var calls []struct {
		Ctx         context.Context
		UserId      uuid.UUID
		OrderNumber objects.OrderNumber
		Operation   objects.Operation
		Amount      objects.Amount
		Timestamp   time.Time
	}
	mock.lockCreateTransactionInTx.RLock()
	calls = mock.calls.CreateTransactionInTx
	mock.lockCreateTransactionInTx.RUnlock()
	return calls
}

// Ensure that MockGetTransactionsRepo does implement GetTransactionsRepo.
// If this is not the case, regenerate this file with mockery.
var _ GetTransactionsRepo = &MockGetTransactionsRepo{}

// MockGetTransactionsRepo is a mock implementation of GetTransactionsRepo.
//
//	func TestSomethingThatUsesGetTransactionsRepo(t *testing.T) {
//
//		// make and configure a mocked GetTransactionsRepo
//		mockedGetTransactionsRepo := &MockGetTransactionsRepo{
//			GetTransactionsFunc: func(ctx context.Context, userId uuid.UUID, operation objects.Operation, offset int32, limit int32) ([]entities.Transaction, error) {
//				panic("mock out the GetTransactions method")
//			},
//		}
//
//		// use mockedGetTransactionsRepo in code that requires GetTransactionsRepo
//		// and then make assertions.
//
//	}
type MockGetTransactionsRepo struct {
	// GetTransactionsFunc mocks the GetTransactions method.
	GetTransactionsFunc func(ctx context.Context, userId uuid.UUID, operation objects.Operation, offset int32, limit int32) ([]entities.Transaction, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetTransactions holds details about calls to the GetTransactions method.
		GetTransactions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserId is the userId argument value.
			UserId uuid.UUID
			// Operation is the operation argument value.
			Operation objects.Operation
			// Offset is the offset argument value.
			Offset int32
			// Limit is the limit argument value.
			Limit int32
		}
	}
	lockGetTransactions sync.RWMutex
}

// GetTransactions calls GetTransactionsFunc.
func (mock *MockGetTransactionsRepo) GetTransactions(ctx context.Context, userId uuid.UUID, operation objects.Operation, offset int32, limit int32) ([]entities.Transaction, error) {
	if mock.GetTransactionsFunc == nil {
		panic("MockGetTransactionsRepo.GetTransactionsFunc: method is nil but GetTransactionsRepo.GetTransactions was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserId    uuid.UUID
		Operation objects.Operation
		Offset    int32
		Limit     int32
	}{
		Ctx:       ctx,
		UserId:    userId,
		Operation: operation,
		Offset:    offset,
		Limit:     limit,
	}
	mock.lockGetTransactions.Lock()
	mock.calls.GetTransactions = append(mock.calls.GetTransactions, callInfo)
	mock.lockGetTransactions.Unlock()
	return mock.GetTransactionsFunc(ctx, userId, operation, offset, limit)
}

// GetTransactionsCalls gets all the calls that were made to GetTransactions.
// Check the length with:
//
//	len(mockedGetTransactionsRepo.GetTransactionsCalls())
func (mock *MockGetTransactionsRepo) GetTransactionsCalls() []struct {
	Ctx       context.Context
	UserId    uuid.UUID
	Operation objects.Operation
	Offset    int32
	Limit     int32
} {
	var calls []struct {
		Ctx       context.Context
		UserId    uuid.UUID
		Operation objects.Operation
		Offset    int32
		Limit     int32
	}
	mock.lockGetTransactions.RLock()
	calls = mock.calls.GetTransactions
	mock.lockGetTransactions.RUnlock()
	return calls
}

// Ensure that MockWithdrawRepo does implement WithdrawRepo.
// If this is not the case, regenerate this file with mockery.
var _ WithdrawRepo = &MockWithdrawRepo{}

// MockWithdrawRepo is a mock implementation of WithdrawRepo.
//
//	func TestSomethingThatUsesWithdrawRepo(t *testing.T) {
//
//		// make and configure a mocked WithdrawRepo
//		mockedWithdrawRepo := &MockWithdrawRepo{
//			CreateOrUpdateBalanceInTxFunc: func(ctx context.Context, userId uuid.UUID, operation objects.Operation, amount objects.Amount, updatedAt time.Time) error {
//				panic("mock out the CreateOrUpdateBalanceInTx method")
//			},
//			CreateTransactionInTxFunc: func(ctx context.Context, userId uuid.UUID, orderNumber objects.OrderNumber, operation objects.Operation, amount objects.Amount, timestamp time.Time) error {
//				panic("mock out the CreateTransactionInTx method")
//			},
//		}
//
//		// use mockedWithdrawRepo in code that requires WithdrawRepo
//		// and then make assertions.
//
//	}
type MockWithdrawRepo struct {
	// CreateOrUpdateBalanceInTxFunc mocks the CreateOrUpdateBalanceInTx method.
	CreateOrUpdateBalanceInTxFunc func(ctx context.Context, userId uuid.UUID, operation objects.Operation, amount objects.Amount, updatedAt time.Time) error

	// CreateTransactionInTxFunc mocks the CreateTransactionInTx method.
	CreateTransactionInTxFunc func(ctx context.Context, userId uuid.UUID, orderNumber objects.OrderNumber, operation objects.Operation, amount objects.Amount, timestamp time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrUpdateBalanceInTx holds details about calls to the CreateOrUpdateBalanceInTx method.
		CreateOrUpdateBalanceInTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserId is the userId argument value.
			UserId uuid.UUID
			// Operation is the operation argument value.
			Operation objects.Operation
			// Amount is the amount argument value.
			Amount objects.Amount
			// UpdatedAt is the updatedAt argument value.
			UpdatedAt time.Time
		}
		// CreateTransactionInTx holds details about calls to the CreateTransactionInTx method.
		CreateTransactionInTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserId is the userId argument value.
			UserId uuid.UUID
			// OrderNumber is the orderNumber argument value.
			OrderNumber objects.OrderNumber
			// Operation is the operation argument value.
			Operation objects.Operation
			// Amount is the amount argument value.
			Amount objects.Amount
			// Timestamp is the timestamp argument value.
			Timestamp time.Time
		}
	}
	lockCreateOrUpdateBalanceInTx sync.RWMutex
	lockCreateTransactionInTx     sync.RWMutex
}

// CreateOrUpdateBalanceInTx calls CreateOrUpdateBalanceInTxFunc.
func (mock *MockWithdrawRepo) CreateOrUpdateBalanceInTx(ctx context.Context, userId uuid.UUID, operation objects.Operation, amount objects.Amount, updatedAt time.Time) error {
	if mock.CreateOrUpdateBalanceInTxFunc == nil {
		panic("MockWithdrawRepo.CreateOrUpdateBalanceInTxFunc: method is nil but WithdrawRepo.CreateOrUpdateBalanceInTx was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		UserId    uuid.UUID
		Operation objects.Operation
		Amount    objects.Amount
		UpdatedAt time.Time
	}{
		Ctx:       ctx,
		UserId:    userId,
		Operation: operation,
		Amount:    amount,
		UpdatedAt: updatedAt,
	}
	mock.lockCreateOrUpdateBalanceInTx.Lock()
	mock.calls.CreateOrUpdateBalanceInTx = append(mock.calls.CreateOrUpdateBalanceInTx, callInfo)
	mock.lockCreateOrUpdateBalanceInTx.Unlock()
	return mock.CreateOrUpdateBalanceInTxFunc(ctx, userId, operation, amount, updatedAt)
}

// CreateOrUpdateBalanceInTxCalls gets all the calls that were made to CreateOrUpdateBalanceInTx.
// Check the length with:
//
//	len(mockedWithdrawRepo.CreateOrUpdateBalanceInTxCalls())
func (mock *MockWithdrawRepo) CreateOrUpdateBalanceInTxCalls() []struct {
	Ctx       context.Context
	UserId    uuid.UUID
	Operation objects.Operation
	Amount    objects.Amount
	UpdatedAt time.Time
} {
	var calls []struct {
		Ctx       context.Context
		UserId    uuid.UUID
		Operation objects.Operation
		Amount    objects.Amount
		UpdatedAt time.Time
	}
	mock.lockCreateOrUpdateBalanceInTx.RLock()
	calls = mock.calls.CreateOrUpdateBalanceInTx
	mock.lockCreateOrUpdateBalanceInTx.RUnlock()
	return calls
}

// CreateTransactionInTx calls CreateTransactionInTxFunc.
func (mock *MockWithdrawRepo) CreateTransactionInTx(ctx context.Context, userId uuid.UUID, orderNumber objects.OrderNumber, operation objects.Operation, amount objects.Amount, timestamp time.Time) error {
	if mock.CreateTransactionInTxFunc == nil {
		panic("MockWithdrawRepo.CreateTransactionInTxFunc: method is nil but WithdrawRepo.CreateTransactionInTx was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UserId      uuid.UUID
		OrderNumber objects.OrderNumber
		Operation   objects.Operation
		Amount      objects.Amount
		Timestamp   time.Time
	}{
		Ctx:         ctx,
		UserId:      userId,
		OrderNumber: orderNumber,
		Operation:   operation,
		Amount:      amount,
		Timestamp:   timestamp,
	}
	mock.lockCreateTransactionInTx.Lock()
	mock.calls.CreateTransactionInTx = append(mock.calls.CreateTransactionInTx, callInfo)
	mock.lockCreateTransactionInTx.Unlock()
	return mock.CreateTransactionInTxFunc(ctx, userId, orderNumber, operation, amount, timestamp)
}

// CreateTransactionInTxCalls gets all the calls that were made to CreateTransactionInTx.
// Check the length with:
//
//	len(mockedWithdrawRepo.CreateTransactionInTxCalls())
func (mock *MockWithdrawRepo) CreateTransactionInTxCalls() []struct {
	Ctx         context.Context
	UserId      uuid.UUID
	OrderNumber objects.OrderNumber
	Operation   objects.Operation
	Amount      objects.Amount
	Timestamp   time.Time
} {
	var calls []struct {
		Ctx         context.Context
		UserId      uuid.UUID
		OrderNumber objects.OrderNumber
		Operation   objects.Operation
		Amount      objects.Amount
		Timestamp   time.Time
	}
	mock.lockCreateTransactionInTx.RLock()
	calls = mock.calls.CreateTransactionInTx
	mock.lockCreateTransactionInTx.RUnlock()
	return calls
}
